### ISSUE TITLE
New login page showing messy and without any style (community 5.0d)

### ISSUE THREAD

**Issue by drisschelouati** [teqnology/alfresco-login-reset#1]
Hi, 
i installed the amps on a fresh community 5.0d (offline windows 7 pc). the amps applied successfully but after server startup, the result is a messy login page without any style (see capture in the attached file). Going to try an install on a fresh 5.0c. However the authentication still works, and there is a new debug menu in the share UI, next to the administration console.

![login-reset-capture](https://cloud.githubusercontent.com/assets/12543068/7746288/98469154-ffa0-11e4-8660-2316d5ee975c.JPG)

**Comment by teqnology** [comment]
Do you have any errors showing on the page? like accessing the web developer tools through F12 and opening the "console" tab? I'd like to see what's the outcome there. Thanks

**Comment by myanes** [comment]
Same problem here, also 5.0.d version running on Centos 7.
And no errors in console tab.

![alfrescologin](https://cloud.githubusercontent.com/assets/5580913/7756260/7467908a-fffa-11e4-9c84-4afe42489087.png)

**Comment by drisschelouati** [comment]
no errors in console tab too. I will try an install on 5.0c soon.

**Comment by drisschelouati** [comment]
I also extracted your customTheme seperatly to test it, it works but there is a problem with the nav bar that displays too wide in black, displaying some search options that should not be displayed, and crops when you click on it.

**Comment by teqnology** [comment]
Hey I've updated the AMP it was a small fix I had to apply as the current AMP were compatible with Alfresco 4.x only. I had to move the assets inside the META-INF/resources folder instead of having them inside the old /web folder as it was handled by Surf before 4.2 came along. Could you try the new -share.amp and let me know if it works for you? I've just validated it and it works :)

**Comment by drisschelouati** [comment]
Hi there,

installed and works on 5.0d, i can validate it too. Awesome work, congratz.
Personnal thougths: this login page lacks of styling, maybe youve done this on purpose so we can configure it and style it at our convenience.

Good job!

**Comment by myanes** [comment]
Working perfectly for me too!
Thanks for your support!!

Personal thoughts: the login page is perfect, elegant and stylish.

**Comment by teqnology** [comment]
Ok I'll close this one then, thanks for your feedback guys. The style is from the material design by google, minimal on purpose. I left the choice to the final user to actually change it if they want. I like it this way though. The main thing was actually create a reset password feature that was more secure (and compatible with Alfresco 5) without showing plain new password in the confirmation email. :)
