### ISSUE TITLE
It doesn't work in 5.0a version.

### ISSUE THREAD

**Issue by m2-satake** [teqnology/alfresco-login-reset#2]
Hi,

I've installed this add-on into the alfresco server(community 5.0a).
However, any email didn't be sent from server when I pressed 'Send Instruction' button.

![screen](https://cloud.githubusercontent.com/assets/13653480/9077876/8b21b0c6-3b6e-11e5-95ff-d08b80c5cf26.png)

I did all the procedures which is described in 'Quick Start' of following page.
Is there any missing procedure in it?
I'd appreciate if you could help me!!

https://github.com/teqnology/alfresco-login-reset

**Comment by teqnology** [comment]
Could you provide any more details about the issue?

Logs maybe? Do you have the email configured? Do you have the ACP from the package extracted into the Data Dictionary email template folder?

**Comment by teqnology** [comment]
I've fixed an issue where the email template path was wrong and send email action was failing. Could you please download the new amp here:
https://github.com/teqnology/alfresco-login-reset-repo/blob/master/target/alfresco-login-reset-repo.amp
and try again please?
Thanks

**Comment by qoitecover** [comment]
Hi,teqnology
I encountered the same problem as m2-satake mentioned.
I just do it as your steps.
I don't know how to get the Logs.
And I don't know how to have the ACP from the package extracted into the Data Dictionary email template folder.
Please tell me how to handle this.

I note Another problem is that if I input my username or email in the page of "password forget"  the tips in the input does not disappear.
How to solve it?

thank you a lot

**Comment by teqnology** [comment]
I'm going to close this one, as we're continuing the discussion here:
`https://github.com/teqnology/alfresco-login-reset/issues/6`
