### ISSUE TITLE
Does it support LDAP?

### ISSUE THREAD

**Issue by olimination** [teqnology/alfresco-login-reset#3]
Hi,
I'm looking for a password change/reset solution for Alfresco Community 5.0d which is using an LDAP (ApacheDS) for synchronizing users and groups.

Does your addon also support updating the passwords in the LDAP?

Thanks for feedback,
Oli

**Comment by teqnology** [comment]
Hello,

Unfortunately, no other Authentication subsystems are supported right now.
As far as I know, LDAP password should be changed within Active Directory
boundaries (and not through third party applications or extensions). I'm
not sure that even default password change feature in Alfresco supports
LDAP password change once set up.

Cheers.
A.

On Wed, 12 Aug 2015 at 21:40 olimination notifications@github.com wrote:

> Hi,
> I'm looking for a password change/reset solution for Alfresco Community
> 5.0d which is using an LDAP (ApacheDS) for synchronizing users and groups.
> 
> Does your addon also support updating the passwords in the LDAP?
> 
> Thanks for feedback,
> Oli
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/teqnology/alfresco-login-reset/issues/3.
> 
> ## 

Sent from my Android Inbox app.

**Comment by olimination** [comment]
Thanks for feedback. According to several articles this is really not supported for the moment.
E.g. http://forums.alfresco.com/forum/end-user-discussions/alfresco-share/change-user-password-02232015-0742

cheers,
Oli
