### ISSUE TITLE
Alfresco in Debug mode after installing

### ISSUE THREAD

**Issue by myanes** [teqnology/alfresco-login-reset#4]
Hi,

Thank you very much for this add-on. Really useful.
The problem I'm facing is that my Alfresco installation start in debug mode after installing the AMPS.
I've tried a clean Alfresco 5.0.d installation, with no others addons, but I get the same behaviour anytime I try to install it.

Thanks in advance.

**Comment by teqnology** [comment]
Hey, thanks for your comment.

When you say starts in debug mode, what do you mean? Your logs start spamming a lot of script rows?

That's because here:

https://github.com/teqnology/alfresco-login-reset-repo/blob/master/src/main/amp/config/alfresco/module/alfresco-login-reset-repo/log4j.properties 
I'm enabling `log4j.logger.org.alfresco.repo.jscript.ScriptLogger=debug`.

Just open your log4j.properties and override this with `info` or `warning`. You can find a sample log4j file in `shared/classed/alfresco/extension`.

Let me know

**Comment by myanes** [comment]
Hi, thanks for your support. 
What I mean by "starting in debug mode" is that suddenly I have a new "Debug menu" in the header which is not a big issue itself. But, after this "Debug menu" is activated I can't use the admin tools anymore (attached images).

![instantanea1](https://cloud.githubusercontent.com/assets/5580913/9665663/96b9a9c2-5269-11e5-927a-cb3598a11b5c.png)
![instantanea2](https://cloud.githubusercontent.com/assets/5580913/9665662/96b8994c-5269-11e5-86bc-22feb93b03d9.png)

Maybe it's an Alfresco 5 issue, but by now it's only happening after installing this addon (the addon it's working perfectly, anyway).

Thanks again.

**Comment by teqnology** [comment]
I need to test it and validate, but as far as I remember, the current
alfresco local release (bitnami or original files), are broken in the admin
console (I can't get it working, blank pages also for me on a default
installation). Regarding debug menu, that's a new Alfresco 5 feature, which
I probably left on, just update your share-config-custom.xml file in your
`tomcat/shared/classes/web-extension` folder with:
`<client-debug>true</client-debug>`

Let me know if this at least fixes your issue.

A.

On Fri, 4 Sep 2015 at 03:30 myanes notifications@github.com wrote:

> Hi, thanks for your support.
> What I mean by "starting in debug mode" is that suddenly I have a new
> "Debug menu" in the header which is not a big issue itself. But, after this
> "Debug menu" is activated I can't use the admin tools anymore (attached
> images).
> 
> [image: instantanea1]
> https://cloud.githubusercontent.com/assets/5580913/9665663/96b9a9c2-5269-11e5-927a-cb3598a11b5c.png
> [image: instantanea2]
> https://cloud.githubusercontent.com/assets/5580913/9665662/96b8994c-5269-11e5-86bc-22feb93b03d9.png
> 
> Maybe it's an Alfresco 5 issue, but by now it's only happening after
> installing this addon (the addon it's working perfectly, anyway).
> 
> Thanks again.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/teqnology/alfresco-login-reset/issues/4#issuecomment-137521171
> .
> 
> ## 

Sent from my Android Inbox app.

**Comment by teqnology** [comment]
I also found out here: 
http://docs.alfresco.com/5.0/concepts/alfresco-sdk-whats-new.html
It's a known bug that now has been solved with Maven 2.1, see What's new in Alfresco SDK 2.1, last element: Fixed blank Admin Console bug

**Comment by myanes** [comment]
Thank you very much for your support. I really appreciate it.
Unfortunately nothing seems to work to solve this blank page, but your addon it's working like a charm, so I'm closing this issue.

Thanks again!

**Comment by teqnology** [comment]
Adding this FYI:

fixed the issue and rebuilt the new amp, if you don't want to reinstall it, this is how to fix it quickly: https://issues.alfresco.com/jira/browse/ALF-9970, there was a known bug where development mode set up in share-config-custom was preventing the admin-console from showing. Hope it helps
