### ISSUE TITLE
Hello, Admin tools page not working

### ISSUE THREAD

**Issue by alahwany** [teqnology/alfresco-login-reset#5]
I have installed your script but i found after installing it and when access the admin tools not working please see the attached files.

i hope to help me to fix this. my version is Alfresco 5.0.d community edition
thanks
and if i want back to old login page with forgot password link on the old page how make that ?

![33](https://cloud.githubusercontent.com/assets/14204438/9978626/bdffbe02-5f3b-11e5-8f06-56dc68fdee41.JPG)

**Comment by teqnology** [comment]
fixed the issue and rebuilt the new amp, if you don't want to reinstall it, this is how to fix it quickly: https://issues.alfresco.com/jira/browse/ALF-9970, there was a known bug where `development` mode set up in share-config-custom was preventing the admin-console from showing. Hope it helps

**Comment by alahwany** [comment]
can you please give me the link for new AMP and i will reinstall it.

i have downloaded the AMP from the below link and after installing it the login page didn't changed !!

https://github.com/teqnology/alfresco-login-reset-share/tree/master/target
https://github.com/teqnology/alfresco-login-reset-repo/tree/master/target
thank you for your respond

**Comment by myanes** [comment]
Working like a Charm Alen, thanks for this.
Superb support.

Thanks again.

**Comment by teqnology** [comment]
Glad I could help. :+1:

**Comment by alahwany** [comment]
can you please tell me how to start work it ? becasue i installed the new AMP on fresh Alfresco community edition 5.0.d and the login didn't changed with this !!!

before your AMP working fine but the admin tools not working now with the new AMP the admin tools working but the login page didn't changed !!! 

can you help me or give me the link to install the AMP for this

**Comment by teqnology** [comment]
You should download this one: `https://github.com/teqnology/alfresco-login-reset-share/tree/master/target`, I've just tested it (downloaded the amp and installed it locally), and it works (both admin console and the login page). Not really sure what's the issue preventing you from viewing the login page.

**Comment by alahwany** [comment]
i will download this from your link now and for repo AMP i will download it again from here
https://github.com/teqnology/alfresco-login-reset-repo/tree/master/target

and install the alfresco again and try to install the AMP again on it and back to you.

regards

**Comment by alahwany** [comment]
![error](https://cloud.githubusercontent.com/assets/14204438/10006503/fa89cee8-60bd-11e5-8ba4-66b084e7ac14.JPG)
it's working fine but the recover of password not working with me and show this error, i have attached the image of this error.

i have configured the mail and i have received the notification from Alfresco like invite user or other things to be sure the mail is working fine.

**Comment by teqnology** [comment]
Hi, Could you please confirm that the `alfresco/bootstrap/alfresco-email-template-bootstrap.acp` has unpacked sucessfully during bootstrap? You should find an email template folder inside this path: `/${spaces.company_home.childname}/${spaces.dictionary.childname}/${spaces.templates.email.childname}`. Check this section for more info and the details path and filenames: https://github.com/teqnology/alfresco-login-reset#acp-bootstrap. If not, just unpack the .acp into the folder and make sure the path is correct as being used here: 

https://github.com/teqnology/alfresco-login-reset-repo/blob/master/src/main/amp/config/alfresco/templates/webscripts/com/androgogic/login/forgot-password/forgot-password-workflow.post.json.js

`mail.parameters.template = companyhome.childByNamePath("Data Dictionary/Email Templates/andro-email-template/forgot-password-email.ftl");`

**Comment by alahwany** [comment]
hello my friend,

i have attached images shown all files 
![code mail](https://cloud.githubusercontent.com/assets/14204438/10011949/70145f5e-6102-11e5-89ab-815fdef52afd.JPG)
![files](https://cloud.githubusercontent.com/assets/14204438/10011950/701e2020-6102-11e5-8743-9f93c222017a.JPG)
![mail template](https://cloud.githubusercontent.com/assets/14204438/10011951/70232bba-6102-11e5-8170-0ef89cc4e082.JPG)

**Comment by teqnology** [comment]
could you please provide logs or at least what's catalina.out output when
send email action fails?

On Tue, Sep 22, 2015, 4:18 PM alahwany notifications@github.com wrote:

> hello my friend,
> 
> i have attached images shown all files
> [image: code mail]
> https://cloud.githubusercontent.com/assets/14204438/10011949/70145f5e-6102-11e5-89ab-815fdef52afd.JPG
> [image: files]
> https://cloud.githubusercontent.com/assets/14204438/10011950/701e2020-6102-11e5-8743-9f93c222017a.JPG
> [image: mail template]
> https://cloud.githubusercontent.com/assets/14204438/10011951/70232bba-6102-11e5-8170-0ef89cc4e082.JPG
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/teqnology/alfresco-login-reset/issues/5#issuecomment-142189663
> .
> 
> ## 

Sent from my Android Inbox app.

**Comment by myanes** [comment]
I'm sorry I spoke too fast.
I'm facing the same issue as alahwany, or similar. The password recovery screen is not showing any error but I never get the instructions email.
In my catalina.out I've found this:

2015-09-21 20:16:49,200  DEBUG [repo.jscript.ScriptLogger] [http-apr-8080-exec-1] forgot-pasword workflow started with name: activiti$activitiAdhoc
 2015-09-21 20:18:49,203  INFO  [webscripts.connector.RemoteClient] [http-apr-8080-exec-10] Exception calling (POST) http://localhost:8080/alfresco/s/androgogic/login/forgot-password
 2015-09-21 20:18:49,206  INFO  [webscripts.connector.RemoteClient] [http-apr-8080-exec-10] Error status 408 Read timed out
 java.net.SocketTimeoutException: Read timed out

I have to say that I receive test email everytime I start Alfresco and the daily feed.

**Comment by alahwany** [comment]
Hello myanes,

ALAHWANY is my name my friend and the screen showing my mail on gmail becasue i have account on alfresco with my mail and when make reset i must receive the instruction mail to set new password for my account on Alfresco.

so this error i don't know from where and i will send my log to my friend Admin of the script to see this error from where.

now i will reinstall again the alfresco community edition 5.0.d and try to install the script with AMP files and send to log to our friend.

regards

**Comment by teqnology** [comment]
I'm looking into it and let you know.

On Wed, Sep 23, 2015, 5:39 AM alahwany notifications@github.com wrote:

> Hello myanes,
> 
> ALAHWANY is my name my friend and the screen showing my mail on gmail
> becasue i have account on alfresco with my mail and when make reset i must
> receive the instruction mail to set new password for my account on Alfresco.
> 
> so this error i don't know from where and i will send my log to my friend
> Admin of the script to see this error from where.
> 
> now i will reinstall again the alfresco community edition 5.0.d and try to
> install the script with AMP files and send to log to our friend.
> 
> regards
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/teqnology/alfresco-login-reset/issues/5#issuecomment-142395918
> .
> 
> ## 

Sent from my Android Inbox app.

**Comment by teqnology** [comment]
Ok just realized the path was completely wrong (as I was doing some refactoring but not completed the task at 100%). My bad and I'm sorry.

I've fixed the issue now and validated the latest amp (no need to update the -share.amp, only the -repo.amp was affected and updated with relevant changes). Could you please download the new amp here:
https://github.com/teqnology/alfresco-login-reset-repo/blob/master/target/alfresco-login-reset-repo.amp
and try again please?
Thanks

**Comment by teqnology** [comment]
I just realised, you should run the apply_amps.sh script with the `-force` attribute otherwise a new test won't actually show you the changes.

**Comment by alahwany** [comment]
thank you very much eng. Alen Subat. for this script and for your support and fix the problems with me on many things in alfresco, i don't know what can i say for really thank you very much. :+1: 
:100: 

i will close this issue and i will donate for this :-)
