### ISSUE TITLE
It does no work on Alfresco5.0d 

### ISSUE THREAD

**Issue by qoitecover** [teqnology/alfresco-login-reset#6]
Hi,teqnology
I encountered the same problem as m2-satake mentioned.
I just do it as your steps.
I don't know how to get the Logs.
And I don't know how to have the ACP from the package extracted into the Data Dictionary email template folder.
Please tell me how to handle this.

I noted Another problem is that if I input my username or email in the page of "password forget" the tips in the input does not disappear.
How to solve it?
![5 38zzt a 2 q u uz_52bh](https://cloud.githubusercontent.com/assets/15119390/10532486/61b9f53e-73f1-11e5-8ca0-2a4f00e9460e.png)

thank you a lot

**Comment by teqnology** [comment]
Did you download the latest amp? the file was updated last week https://github.com/teqnology/alfresco-login-reset-repo/tree/master/target so if you have an earlier version it won't work on Alfresco installation different than English language. If you have the last version: could you please open the developer console on your browser (if you use Chrom just press F12 (or right click on the page then click on "Inspect Element". Open the "Console tab" and reload the page. Check that you're not getting any errors in the console. Are you able to provide more info after doing so? Thanks.
Also: if you want to apply your own changes to the HTML, just browse to this folder:
`tomcat/webapps/share/WEB-INF/classes/alfresco/templates/com/androgogic/base/login/` and you'll find all the files, the header needs to be changes in all three FTL files: forgot-password, reset-password and login. Better if you copy those files into `tomcat/shared/classes/web-extensions/templates/com/androgogic/base/login/`. Let me know. Thanks.

**Comment by qoitecover** [comment]
Hi,teqnology
I did it as you say in last mail.
I downloaded the latest version of this add-ons.
these are the logs :
![s4ahrnr6 0ad f vw q s](https://cloud.githubusercontent.com/assets/15119390/10536324/b123c188-741c-11e5-9bc4-8ad4199e0b25.png)

here are my two amp files downloaded from your sites:
![9 4 3 ao 3n7 k1z rgbg](https://cloud.githubusercontent.com/assets/15119390/10536341/d2595228-741c-11e5-8378-230e2d5bc690.png)

I think I have nothing wrong doing it by your steps....

waiting for your reply,thanks!

**Comment by teqnology** [comment]
That's a problem on your end. The google domain  is probably blocked from
where are you trying to reach it:
http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js
this is perfectly working for me.
Can you update the ftl to include a local version of the same jquery min
file?

On Fri, 16 Oct 2015 at 18:44 qoitecover notifications@github.com wrote:

> Hi,teqnology
> I did it as you say in last mail.
> I downloaded the latest version of this add-ons.
> these are the logs :
> [image: s4ahrnr6 0ad f vw q s]
> https://cloud.githubusercontent.com/assets/15119390/10536324/b123c188-741c-11e5-9bc4-8ad4199e0b25.png
> 
> here are my two amp files downloaded from your sites:
> [image: 9 4 3 ao 3n7 k1z rgbg]
> https://cloud.githubusercontent.com/assets/15119390/10536341/d2595228-741c-11e5-8378-230e2d5bc690.png
> 
> I think I have nothing wrong doing it by your steps....
> 
> waiting for your reply,thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/teqnology/alfresco-login-reset/issues/6#issuecomment-148639903
> .
> 
> ## 

Sent from my Android Inbox app.

**Comment by qoitecover** [comment]
well,I've got the jquery-min.js.
And I copy that jquery-min.js into my local jquery-min.js file.
Then there is nothing happened When I run my Alfresco Again.
Did I miss somethings?  
![vfr0 otcnt f v_47xc 12](https://cloud.githubusercontent.com/assets/15119390/10537918/9042ef88-7427-11e5-9339-877182d42518.jpg)

Please tell me more.....
my thanks to you!!!

**Comment by teqnology** [comment]
You need to change the ftl files to actually point to your local jquery instead of the google hosted one. Did you do that? Thanks
