### ISSUE TITLE
Encoding of the reset URL(@ replaced by %40)

### ISSUE THREAD

**Issue by jamilnour** [teqnology/alfresco-login-reset#7]
On PC browser when you click on the reset URL from the email the email address parameter inside the GET URL has %40 and not @ which cause the user not found in the change password page.

**Comment by teqnology** [comment]
Icould you please let me know if this fixes this issue? I really couldn't test it properly as I don't experience the same issue as you (prob different env or browser versions?)

**Comment by jamilnour** [comment]
Yes it works now for all the browsers I tested with (IE, FF and Chrome)

**Comment by teqnology** [comment]
Thank you for confirming. Closing now
