### ISSUE TITLE
 Changing the password of another email

### ISSUE THREAD

**Issue by jamilnour** [teqnology/alfresco-login-reset#8]
I applied a forget password to myself and when I receive the link I clicked and changed the email fromnthe GET URL to another known to the system and the server changes the password for the other email without any problem!!!

**Comment by ghost** [comment]
Email addresses muts be unique in Alfresco.

**Comment by teqnology** [comment]
Not really true, only the `userName` is unique inside Alfresco default authentication subsystem. The entire point of this extension module is because we had many cases of multiple accounts with the same email but different usernames

**Comment by teqnology** [comment]
Could you please let me know if this is working now? I've changed the way cross checks work now (using user preferences and set|getPreferences() methods withing Alfresco's APIs). I've tested it locally and it appears to be working. Thanks

**Comment by jamilnour** [comment]
yes it works now and I got the message of "No reset password..." when manually I changed the email from the URL

**Comment by teqnology** [comment]
Thank you for confirming. Closing now
